// Generated by CoffeeScript 1.4.0
var app, assets, express, fs, http, jog, port, printer, redback, rest, stylus, uploadPrintJob, util;

require('longjohn');

require('sugar');

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

http = require('http');

util = require('util');

rest = require('../node_modules/restler/lib/restler');

redback = require('redback').createClient();

fs = require('fs');

printer = redback.createHash('printer');

app = express();

app.use(express.compress());

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.use(express.bodyParser({
  keepExtensions: true,
  uploadDir: "" + __dirname + "/uploads",
  hash: "sha1"
}));

app.use(express.cookieParser());

app.set('view engine', 'jade');

app.get('/', function(req, resp) {
  return resp.render('index');
});

jog = function(req, resp, next) {
  var axis, distance, speed, url;
  axis = req.param('axis');
  distance = req.param('distance');
  speed = req.param('speed');
  url = "http://admin:password@localhost:4311/move/axis/" + axis + "/" + distance + "/" + (speed * 60);
  return rest.get(url).on("success", function(data, res) {
    console.log(data);
    return next();
  });
};

app.put('/jog', jog, function(req, resp) {
  return resp.send(200);
});

uploadPrintJob = function(req, resp, next) {
  var data, files, url;
  console.log(req.files);
  files = req.files.printjobs;
  next();
  if (false) {
    url = "http://admin:password@localhost:4311/printbutton";
    data = {
      filename: "./test.gcode"
    };
    return rest.get(url).on("success", {
      data: data
    }, function(data, res) {
      console.log(data);
      return next();
    });
  }
};

app.post('/print_jobs/', uploadPrintJob, function(req, resp) {
  return resp.send(200);
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3009;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
