// Generated by CoffeeScript 1.4.0
var PrintDriver, PrintQueue, driver;

PrintDriver = (function() {

  function PrintDriver() {}

  PrintDriver.prototype.jog = function(opts, callback) {
    var url;
    url = "http://admin:password@localhost:4311/move/axis/" + opts.axis + "/" + opts.distance + "/" + (opts.speed * 60);
    return rest.get(url).on("success", function(data, res) {
      console.log(data);
      return callback();
    });
  };

  return PrintDriver;

})();

PrintQueue = (function() {

  function PrintQueue(d) {
    this.driver = driver;
  }

  PrintQueue.prototype.add = function(files, callback) {
    return callback();
  };

  PrintQueue.prototype.print = function() {
    var data, url;
    url = "http://admin:password@localhost:4311/printbutton";
    data = {
      filename: "./test.gcode"
    };
    return rest.get(url).on("success", {
      data: data
    }, function(data, res) {
      console.log(data);
      return callback();
    });
  };

  return PrintQueue;

})();

module.exports = {
  driver: (driver = new PrintDriver()),
  queue: new PrintQueue(driver)
};
