// Generated by CoffeeScript 1.4.0
var PrintDriver, PrintQueue, driver, rest;

rest = require('../node_modules/restler/lib/restler');

PrintDriver = (function() {

  function PrintDriver() {}

  PrintDriver.prototype.jog = function(opts, callback) {
    var url;
    url = "http://admin:password@localhost:4311/move/axis/" + opts.axis + "/" + opts.distance + "/" + (opts.speed * 60);
    return rest.get(url).on("success", function(data, res) {
      console.log(data);
      return callback();
    });
  };

  return PrintDriver;

})();

PrintQueue = (function() {

  function PrintQueue(d) {
    this.driver = driver;
    this.printJobs = [];
  }

  PrintQueue.prototype.add = function(files, callback) {
    this.printJobs.push(files.path);
    return this.print(callback);
  };

  PrintQueue.prototype.print = function(callback) {
    var data, url;
    url = "http://admin:password@localhost:4311/printbutton";
    data = {
      filename: this.printJobs.pop()
    };
    console.log("printing " + data.filename);
    return rest.get(url, {
      data: data
    }).on("success", function(data, res) {
      console.log(data);
      return typeof callback === "function" ? callback() : void 0;
    });
  };

  return PrintQueue;

})();

module.exports = {
  driver: (driver = new PrintDriver()),
  queue: new PrintQueue(driver)
};
